name: Sales Intel Orchestration Automation

on:
  schedule:
    - cron: '0 */5 * * *'
  push:
    branches: [master]
  release:
    types: [created] 

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test with Maven
        run: |
          mvn clean install test
          
      - name: Execution Results Upload Artifact For Cucumber Reporting
        if: always()
        uses: actions/upload-artifact@v3
        with: 
              name: Cucumber Report Latest Results
              path: src/main/resources/Reports/CucumberReports/cucumber-html-reports/
          
      - name: Execution Results Download Artifact For Cucumber Reporting
        if: always()
        uses: actions/download-artifact@v3
        with:
          name: Cucumber Report Latest Results
          
      - name: Execution Results Upload Artifact For Extent Report
        if: always()
        uses: actions/upload-artifact@v3
        with: 
              name: Extent Report Latest Results
              path: test-output/spark/              

      - name: Execution Results Download Artifact For Extent Report
        if: always()
        uses: actions/download-artifact@v3
        with:
          name: Extent Report Latest Results
          
      - name: Execution Results Download Artifact File List
        if: always()
        run: ls -R
        
      - name: Zip Package
        if: always()
        uses: papeloto/action-zip@v1
        with:
            files: test-output/spark/
            dest: Extent_Report.zip
        
      - name: Send mail
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          connection_url: ${{secrets.MAIL_CONNECTION}}
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: Sales Intel Orchestration CI/CD Automation Result
          to:  muthu.kumar@astegic.com
          from: muthumak@gmail.com
          html_body: |
                  <html>
                  <body>
                  <p>Hi Team</p>
                  <p>Please find the Sales Intel Portal Orchestration Automation Test Result:</p>
                  <p>Build Job No:${{github.run_number}} and Job Status:${{job.status}} and the Execution is completed successfully!</p>
                  <p>Thanks</p>
                  <p>Muthukumar</p>
                  </body>
                  </html>
          ignore_cert: true
          convert_markdown: true
          content_type: application/zip
          attachments: target/surefire-reports/Suite/Test.html,target/surefire-reports/emailable-report.html
          priority: high
